// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SmartOrderSystem.Data;

#nullable disable

namespace SmartOrderSystem.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260818032549_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("SmartOrderSystem.Models.Admin", b =>
                {
                    b.Property<int>("admin_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("admin_id");

                    b.Property<string>("email")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("email");

                    b.Property<string>("full_name")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("full_name");

                    b.Property<string>("password_hash")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("password_hash");

                    b.HasKey("admin_id");

                    b.ToTable("admins");
                });

            modelBuilder.Entity("SmartOrderSystem.Models.Customer", b =>
                {
                    b.Property<int>("customer_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("customer_id");

                    b.Property<string>("contact_number")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("contact_number");

                    b.Property<string>("email")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("email");

                    b.Property<string>("full_name")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("full_name");

                    b.Property<string>("password_hash")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("password_hash");

                    b.HasKey("customer_id");

                    b.ToTable("customers");
                });

            modelBuilder.Entity("SmartOrderSystem.Models.CustomerAddress", b =>
                {
                    b.Property<int>("address_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("address_id");

                    b.Property<string>("address_type")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("address_type");

                    b.Property<string>("barangay")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("barangay");

                    b.Property<string>("city")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("city");

                    b.Property<string>("contact_number")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("contact_number");

                    b.Property<DateTime>("created_at")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("created_at");

                    b.Property<int>("customer_id")
                        .HasColumnType("int")
                        .HasColumnName("customer_id");

                    b.Property<bool>("is_default")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("is_default");

                    b.Property<string>("landmark")
                        .HasColumnType("longtext")
                        .HasColumnName("landmark");

                    b.Property<string>("postal_code")
                        .HasColumnType("longtext")
                        .HasColumnName("postal_code");

                    b.Property<string>("province")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("province");

                    b.Property<string>("recipient_name")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("recipient_name");

                    b.Property<string>("street_address")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("street_address");

                    b.Property<DateTime>("updated_at")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("updated_at");

                    b.HasKey("address_id");

                    b.HasIndex("customer_id");

                    b.ToTable("customer_addresses");
                });

            modelBuilder.Entity("SmartOrderSystem.Models.Notification", b =>
                {
                    b.Property<int>("notification_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<DateTime>("created_at")
                        .HasColumnType("datetime(6)");

                    b.Property<int?>("customer_id")
                        .HasColumnType("int");

                    b.Property<bool>("is_read")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("message")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("order_id")
                        .HasColumnType("int");

                    b.Property<string>("type")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("notification_id");

                    b.HasIndex("order_id");

                    b.ToTable("Notifications");
                });

            modelBuilder.Entity("SmartOrderSystem.Models.Order", b =>
                {
                    b.Property<int>("order_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("order_id");

                    b.Property<int?>("address_id")
                        .HasColumnType("int")
                        .HasColumnName("address_id");

                    b.Property<string>("cancellation_reason")
                        .HasColumnType("longtext")
                        .HasColumnName("cancellation_reason");

                    b.Property<string>("courier")
                        .HasColumnType("longtext")
                        .HasColumnName("courier");

                    b.Property<int>("customer_id")
                        .HasColumnType("int")
                        .HasColumnName("customer_id");

                    b.Property<DateTime>("order_date")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("order_date");

                    b.Property<string>("payment_method")
                        .HasColumnType("longtext")
                        .HasColumnName("payment_method");

                    b.Property<string>("payment_status")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("payment_status");

                    b.Property<string>("shipping_status")
                        .HasColumnType("longtext")
                        .HasColumnName("shipping_status");

                    b.Property<string>("status")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("status");

                    b.Property<decimal>("total_amount")
                        .HasColumnType("decimal(65,30)")
                        .HasColumnName("total_amount");

                    b.Property<string>("tracking_number")
                        .HasColumnType("longtext")
                        .HasColumnName("tracking_number");

                    b.Property<DateTime?>("updated_at")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("updated_at");

                    b.HasKey("order_id");

                    b.HasIndex("customer_id");

                    b.ToTable("orders");
                });

            modelBuilder.Entity("SmartOrderSystem.Models.OrderItem", b =>
                {
                    b.Property<int>("order_item_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("order_item_id");

                    b.Property<int>("inventory_id")
                        .HasColumnType("int")
                        .HasColumnName("inventory_id");

                    b.Property<decimal>("item_price")
                        .HasColumnType("decimal(65,30)")
                        .HasColumnName("item_price");

                    b.Property<int>("order_id")
                        .HasColumnType("int")
                        .HasColumnName("order_id");

                    b.Property<int>("quantity")
                        .HasColumnType("int")
                        .HasColumnName("quantity");

                    b.HasKey("order_item_id");

                    b.HasIndex("inventory_id");

                    b.HasIndex("order_id");

                    b.ToTable("order_items");
                });

            modelBuilder.Entity("SmartOrderSystem.Models.ProductImage", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    b.Property<int>("DisplayOrder")
                        .HasColumnType("int")
                        .HasColumnName("display_order");

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("file_name");

                    b.Property<string>("FilePath")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("file_path");

                    b.Property<long>("FileSize")
                        .HasColumnType("bigint")
                        .HasColumnName("file_size");

                    b.Property<bool>("IsCover")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("is_cover");

                    b.Property<int>("ShoeCatalogId")
                        .HasColumnType("int")
                        .HasColumnName("shoe_catalog_id");

                    b.HasKey("Id");

                    b.HasIndex("ShoeCatalogId");

                    b.ToTable("product_images");
                });

            modelBuilder.Entity("SmartOrderSystem.Models.ProductPromotion", b =>
                {
                    b.Property<int>("promotion_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("campaign_name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<decimal>("discount_percentage")
                        .HasColumnType("decimal(65,30)");

                    b.Property<DateTime>("end_date")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("shoe_id")
                        .HasColumnType("int");

                    b.Property<DateTime>("start_date")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("status")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("promotion_id");

                    b.HasIndex("shoe_id");

                    b.ToTable("product_promotions");
                });

            modelBuilder.Entity("SmartOrderSystem.Models.Reservation", b =>
                {
                    b.Property<int>("reservation_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("reservation_id");

                    b.Property<DateTime?>("approved_at")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("approved_at");

                    b.Property<int?>("approved_by")
                        .HasColumnType("int")
                        .HasColumnName("approved_by");

                    b.Property<int?>("converted_order_id")
                        .HasColumnType("int")
                        .HasColumnName("converted_order_id");

                    b.Property<int>("customer_id")
                        .HasColumnType("int")
                        .HasColumnName("customer_id");

                    b.Property<DateTime?>("expires_at")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("expires_at");

                    b.Property<int>("inventory_id")
                        .HasColumnType("int")
                        .HasColumnName("inventory_id");

                    b.Property<int>("quantity")
                        .HasColumnType("int")
                        .HasColumnName("quantity");

                    b.Property<DateTime>("reservation_date")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("reservation_date");

                    b.Property<string>("status")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("status");

                    b.HasKey("reservation_id");

                    b.HasIndex("customer_id");

                    b.HasIndex("inventory_id");

                    b.ToTable("reservations");
                });

            modelBuilder.Entity("SmartOrderSystem.Models.ShoeCatalog", b =>
                {
                    b.Property<int>("shoe_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("shoe_id");

                    b.Property<string>("brand")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("brand");

                    b.Property<string>("category")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("category");

                    b.Property<string>("color")
                        .HasColumnType("longtext")
                        .HasColumnName("color");

                    b.Property<decimal>("default_price")
                        .HasColumnType("decimal(65,30)")
                        .HasColumnName("default_price");

                    b.Property<string>("image_path")
                        .HasColumnType("longtext")
                        .HasColumnName("image_path");

                    b.Property<string>("model_name")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("model_name");

                    b.Property<string>("status")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("status");

                    b.HasKey("shoe_id");

                    b.ToTable("shoes_catalog");
                });

            modelBuilder.Entity("SmartOrderSystem.Models.ShoeInventory", b =>
                {
                    b.Property<int>("inventory_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("inventory_id");

                    b.Property<int>("quantity_in_stock")
                        .HasColumnType("int");

                    b.Property<int>("shoe_id")
                        .HasColumnType("int")
                        .HasColumnName("shoe_id");

                    b.Property<decimal>("size")
                        .HasColumnType("decimal(65,30)");

                    b.HasKey("inventory_id");

                    b.HasIndex("shoe_id");

                    b.ToTable("shoe_inventory");
                });

            modelBuilder.Entity("SmartOrderSystem.Models.CustomerAddress", b =>
                {
                    b.HasOne("SmartOrderSystem.Models.Customer", "Customer")
                        .WithMany()
                        .HasForeignKey("customer_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Customer");
                });

            modelBuilder.Entity("SmartOrderSystem.Models.Notification", b =>
                {
                    b.HasOne("SmartOrderSystem.Models.Order", "Order")
                        .WithMany()
                        .HasForeignKey("order_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Order");
                });

            modelBuilder.Entity("SmartOrderSystem.Models.Order", b =>
                {
                    b.HasOne("SmartOrderSystem.Models.Customer", "Customer")
                        .WithMany()
                        .HasForeignKey("customer_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Customer");
                });

            modelBuilder.Entity("SmartOrderSystem.Models.OrderItem", b =>
                {
                    b.HasOne("SmartOrderSystem.Models.ShoeInventory", "ShoeInventory")
                        .WithMany()
                        .HasForeignKey("inventory_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SmartOrderSystem.Models.Order", "Order")
                        .WithMany("OrderItems")
                        .HasForeignKey("order_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Order");

                    b.Navigation("ShoeInventory");
                });

            modelBuilder.Entity("SmartOrderSystem.Models.ProductImage", b =>
                {
                    b.HasOne("SmartOrderSystem.Models.ShoeCatalog", "ShoeCatalog")
                        .WithMany("Images")
                        .HasForeignKey("ShoeCatalogId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ShoeCatalog");
                });

            modelBuilder.Entity("SmartOrderSystem.Models.ProductPromotion", b =>
                {
                    b.HasOne("SmartOrderSystem.Models.ShoeCatalog", "Shoe")
                        .WithMany()
                        .HasForeignKey("shoe_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Shoe");
                });

            modelBuilder.Entity("SmartOrderSystem.Models.Reservation", b =>
                {
                    b.HasOne("SmartOrderSystem.Models.Customer", "Customer")
                        .WithMany()
                        .HasForeignKey("customer_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SmartOrderSystem.Models.ShoeInventory", "ShoeInventory")
                        .WithMany()
                        .HasForeignKey("inventory_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Customer");

                    b.Navigation("ShoeInventory");
                });

            modelBuilder.Entity("SmartOrderSystem.Models.ShoeInventory", b =>
                {
                    b.HasOne("SmartOrderSystem.Models.ShoeCatalog", "ShoeCatalog")
                        .WithMany()
                        .HasForeignKey("shoe_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ShoeCatalog");
                });

            modelBuilder.Entity("SmartOrderSystem.Models.Order", b =>
                {
                    b.Navigation("OrderItems");
                });

            modelBuilder.Entity("SmartOrderSystem.Models.ShoeCatalog", b =>
                {
                    b.Navigation("Images");
                });
#pragma warning restore 612, 618
        }
    }
}
